export {default as Navbar} from './Navbar'
export {default as Allposts} from './Allposts'
export {default as Login} from './Login'
export {default as Register} from './Register'
export {default as Home} from './Home'